<?php

namespace GeneroWP\MCP\Abilities;

use WP_Error;

/**
 * Send email via wp_mail. ALWAYS requires user approval — the approval
 * prompt shows the full recipient list, subject, and body preview so the
 * user can spot:
 *   - prompt-injected exfiltration attempts (sensitive data → stranger)
 *   - phishing / spam generated by manipulated LLM
 *   - typos in recipient addresses
 *
 * Unlike web-fetch there is NO trust-list: every send is approved.
 * The "From" address is ALWAYS the site default (wp_mail default) — the
 * LLM can't set it, which blocks spoofing.
 */
final class MailSendAbility
{
    /** Hard per-user/day cap to contain spam damage from a rogue chat. */
    private const DAILY_SEND_LIMIT = 20;

    private const DAILY_COUNTER_META = '_gds_mcp_mail_sent_today';

    public static function register(): void
    {
        HelpAbility::registerAbility('gds/mail-send', [
            'label' => 'Send Email',
            'description' => 'Send an email via wp_mail. Requires user approval for every send — the approval prompt shows the full recipient list, subject, and body. The From address is always the site default (LLM cannot override it). Use for customer replies, internal notifications, report delivery.',
            'category' => 'gds-content',
            'input_schema' => [
                'type' => 'object',
                'properties' => [
                    'to' => [
                        'type' => 'array',
                        'items' => ['type' => 'string'],
                        'description' => 'Recipient email addresses. Prefer one at a time to keep the approval prompt scannable.',
                    ],
                    'cc' => [
                        'type' => 'array',
                        'items' => ['type' => 'string'],
                        'description' => 'Optional CC recipients.',
                    ],
                    'bcc' => [
                        'type' => 'array',
                        'items' => ['type' => 'string'],
                        'description' => 'Optional BCC recipients. Visible in the approval prompt — use sparingly.',
                    ],
                    'reply_to' => [
                        'type' => 'string',
                        'description' => 'Optional Reply-To header (single address). Useful when the recipient should reply to a support mailbox rather than the From address.',
                    ],
                    'subject' => [
                        'type' => 'string',
                        'description' => 'Email subject line.',
                    ],
                    'body' => [
                        'type' => 'string',
                        'description' => 'Email body. Plain text by default; set html=true for HTML content.',
                    ],
                    'html' => [
                        'type' => 'boolean',
                        'description' => 'When true, body is treated as HTML (Content-Type: text/html). Defaults to false (plain text).',
                    ],
                ],
                'required' => ['to', 'subject', 'body'],
                'additionalProperties' => false,
            ],
            'output_schema' => [
                'type' => 'object',
                'properties' => [
                    'sent' => ['type' => 'boolean'],
                    'to' => ['type' => 'array'],
                    'subject' => ['type' => 'string'],
                    'remaining_today' => ['type' => 'integer'],
                ],
            ],
            'permission_callback' => [self::class, 'permissionCheck'],
            'execute_callback' => [self::class, 'execute'],
            'meta' => [
                'annotations' => [
                    'readonly' => false,
                    // Always require approval — every send is scrutinized.
                    // The approval prompt displays the full input including
                    // recipients and subject so the user can catch bad sends.
                    'destructive' => true,
                    'idempotent' => false,
                ],
            ],
        ]);
    }

    public static function permissionCheck(): bool
    {
        // Sending email is admin-only. Tighter than the default `read` check.
        return current_user_can('manage_options');
    }

    public static function execute(mixed $input = []): array|WP_Error
    {
        $input = (array) ($input ?? []);

        $to = self::validateAddresses($input['to'] ?? [], 'to');
        if (is_wp_error($to)) {
            return $to;
        }
        if (empty($to)) {
            return new WP_Error('missing_to', 'At least one "to" recipient is required.');
        }

        $cc = self::validateAddresses($input['cc'] ?? [], 'cc');
        if (is_wp_error($cc)) {
            return $cc;
        }
        $bcc = self::validateAddresses($input['bcc'] ?? [], 'bcc');
        if (is_wp_error($bcc)) {
            return $bcc;
        }

        $subject = trim((string) ($input['subject'] ?? ''));
        if ($subject === '') {
            return new WP_Error('missing_subject', 'Subject is required.');
        }
        $body = (string) ($input['body'] ?? '');
        if ($body === '') {
            return new WP_Error('missing_body', 'Body is required.');
        }

        $replyTo = trim((string) ($input['reply_to'] ?? ''));
        if ($replyTo !== '' && ! is_email($replyTo)) {
            return new WP_Error('invalid_reply_to', 'reply_to must be a valid email address.');
        }

        // Per-user per-day cap — contains damage from a rogue chat that
        // somehow gets approval-bombed. Bypassable by admins who reset the
        // counter; intended as a speed-bump, not a hard security gate.
        $remaining = self::decrementDailyCounter();
        if ($remaining < 0) {
            return new WP_Error(
                'daily_limit_reached',
                sprintf('Daily email limit of %d reached for this user. Try again tomorrow.', self::DAILY_SEND_LIMIT)
            );
        }

        // Build headers. NEVER accept "From" from input — always use site default.
        $headers = [];
        if (! empty($input['html'])) {
            $headers[] = 'Content-Type: text/html; charset=UTF-8';
        }
        if (! empty($cc)) {
            $headers[] = 'Cc: '.implode(', ', $cc);
        }
        if (! empty($bcc)) {
            $headers[] = 'Bcc: '.implode(', ', $bcc);
        }
        if ($replyTo !== '') {
            $headers[] = 'Reply-To: '.$replyTo;
        }

        $sent = wp_mail($to, $subject, $body, $headers);

        if (! $sent) {
            // wp_mail returns false on failure — roll back the counter.
            self::incrementDailyCounter();

            return new WP_Error(
                'send_failed',
                'wp_mail() returned false. Check the site\'s mail transport (SMTP plugin, server config, or wp_mail_failed hook).'
            );
        }

        return [
            'sent' => true,
            'to' => $to,
            'subject' => $subject,
            'remaining_today' => max(0, $remaining),
        ];
    }

    /**
     * Validate a list of addresses; reject the whole call if any are
     * malformed (safer than silently dropping one).
     *
     * @return string[]|WP_Error
     */
    private static function validateAddresses(mixed $input, string $field): array|WP_Error
    {
        if (is_string($input)) {
            $input = [$input];
        }
        if (! is_array($input)) {
            return [];
        }
        $out = [];
        foreach ($input as $addr) {
            $addr = trim((string) $addr);
            if ($addr === '') {
                continue;
            }
            if (! is_email($addr)) {
                return new WP_Error(
                    'invalid_address',
                    sprintf('"%s" is not a valid email address in field "%s".', $addr, $field)
                );
            }
            $out[] = $addr;
        }

        return $out;
    }

    /**
     * Decrement today's remaining-send counter and return the new value.
     * Uses user meta keyed by date so the count resets at midnight.
     * Returns -1 when the limit is already exhausted.
     */
    private static function decrementDailyCounter(): int
    {
        $userId = get_current_user_id();
        $today = wp_date('Y-m-d');
        $key = self::DAILY_COUNTER_META.'_'.$today;

        // Clear stale keys from previous days to avoid meta bloat.
        self::cleanupStaleCounters($userId, $today);

        $sent = (int) get_user_meta($userId, $key, true);
        if ($sent >= self::DAILY_SEND_LIMIT) {
            return -1;
        }
        update_user_meta($userId, $key, $sent + 1);

        return self::DAILY_SEND_LIMIT - ($sent + 1);
    }

    private static function incrementDailyCounter(): void
    {
        $userId = get_current_user_id();
        $today = wp_date('Y-m-d');
        $key = self::DAILY_COUNTER_META.'_'.$today;
        $sent = (int) get_user_meta($userId, $key, true);
        if ($sent > 0) {
            update_user_meta($userId, $key, $sent - 1);
        }
    }

    private static function cleanupStaleCounters(int $userId, string $today): void
    {
        global $wpdb;
        $prefix = self::DAILY_COUNTER_META.'_';
        $todayKey = $prefix.$today;
        // phpcs:disable WordPress.DB.DirectDatabaseQuery
        $wpdb->query($wpdb->prepare(
            "DELETE FROM {$wpdb->usermeta}
             WHERE user_id = %d
             AND meta_key LIKE %s
             AND meta_key != %s",
            $userId,
            $wpdb->esc_like($prefix).'%',
            $todayKey
        ));
    }
}
